import OpenStreetMapToilets
import CamdenToilets
import RichmondToilets
import SuttonToilets
import RedbridgeToilets
import LewishamToilets
import LambethToilets
import HealthmaticToilets
import KensingtonChelseaToilets
import BromleyToilets
import NewhamToilets
import BarnetToilets2
import WestminsterToilets
import BrentToilets
import HaringeyToilets
import SouthwarkToilets

# OpenStreetMapToilets.get_openstreetmap_data()
# OpenStreetMapToilets.write_filtered_json()
# CamdenToilets.camden_csv_to_json()
# RichmondToilets.get_richmond_data()
# RichmondToilets.write_cleaned_data_richmond()
# SuttonToilets.sutton_excel_to_json()
# RedbridgeToilets.redbridge_excel_to_json()
# LewishamToilets.lewisham_excel_to_json()
# LambethToilets.lambeth_excel_to_json()
# HealthmaticToilets.healthmatic_excel_to_json()
# KensingtonChelseaToilets.kensington_data_to_json()
# BromleyToilets.extract_bromley_json()
# NewhamToilets.extract_all_newham_toilets()
# BarnetToilets2.barnet_libraries_csv_to_json()
# WestminsterToilets.westminster_csv_to_json()
# BrentToilets.get_all_brent_toilets()
# HaringeyToilets.get_haringey_data()
SouthwarkToilets.get_southwark_data()