import OpenStreetMapToilets
import CamdenToilets
import RichmondToilets
import SuttonToilets
import RedbridgeToilets

OpenStreetMapToilets.get_openstreetmap_data()
OpenStreetMapToilets.write_filtered_json()
CamdenToilets.camden_csv_to_json()
RichmondToilets.get_richmond_data()
RichmondToilets.write_cleaned_data_richmond()
SuttonToilets.sutton_excel_to_json()
RedbridgeToilets.redbridge_excel_to_json()
